Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 168, in wrapped
    return loop.run_until_complete(inner)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from myst_nb import glue
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches


f,ax = plt.subplots()
ax.set_xlim([-0.,3.3])
ax.set_ylim([-0.1,2.1])
ax.set_axis_off()
ax.plot([0,3],[0,0],color='black')
ax.plot([3,3],[0,2],color='black')
ax.plot([0,3],[0,2],color='black')

ax.annotate("a",(3,1.2),horizontalalignment="left")
ax.annotate("b", (1.5,-0.1),verticalalignment="top")
ax.annotate("c", (1.5,1.3))
ax.annotate(r"$\theta$", (0.25,0.1),color="red")
pac = mpatches.Arc([0, 0], 0.5, 0.5, angle=0, theta1=0, theta2=33.69.,color="red")
ax.add_patch(pac)

glue("geom_vector", f, display=False)
------------------


[0;36m  Cell [0;32mIn[4], line 19[0;36m[0m
[0;31m    pac = mpatches.Arc([0, 0], 0.5, 0.5, angle=0, theta1=0, theta2=33.69.,color="red")[0m
[0m                                                                         ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid syntax


