Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 168, in wrapped
    return loop.run_until_complete(inner)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Matrix creation (2d)

## by extension
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

## constant and random initialization
A = np.zeros( (10,10) )
A = np.ones( (7,7) )
A = np.full( (12,12) ,-2)
A = np.random.random( (5,5) )

## Matrix indexing
i33 = A[3,3]    #indexes an element value
l2  = A[2]      #indexes a line
l2  = A[2,:]    #indexes a line
c1  = A[:,1]    #indexes a column
B   = A[:2,:3]  #slices a submatrix

## Matrix structural manipulation
x = np.ones( (3,2) )
y = np.zeros( (3,) )
z = np.ones( (2,4) )

r = np.stack([x,y])
s = np.concatenate( [y,z] )


------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[3], line 24[0m
[1;32m     21[0m y [38;5;241m=[39m np[38;5;241m.[39mzeros( ([38;5;241m3[39m,) )
[1;32m     22[0m z [38;5;241m=[39m np[38;5;241m.[39mones( ([38;5;241m2[39m,[38;5;241m4[39m) )
[0;32m---> 24[0m r [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mstack[49m[43m([49m[43m[[49m[43mx[49m[43m,[49m[43my[49m[43m][49m[43m)[49m
[1;32m     25[0m s [38;5;241m=[39m np[38;5;241m.[39mconcatenate( [y,z] )

File [0;32m<__array_function__ internals>:180[0m, in [0;36mstack[0;34m(*args, **kwargs)[0m

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/core/shape_base.py:426[0m, in [0;36mstack[0;34m(arrays, axis, out)[0m
[1;32m    424[0m shapes [38;5;241m=[39m {arr[38;5;241m.[39mshape [38;5;28;01mfor[39;00m arr [38;5;129;01min[39;00m arrays}
[1;32m    425[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(shapes) [38;5;241m!=[39m [38;5;241m1[39m:
[0;32m--> 426[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m'[39m[38;5;124mall input arrays must have the same shape[39m[38;5;124m'[39m)
[1;32m    428[0m result_ndim [38;5;241m=[39m arrays[[38;5;241m0[39m][38;5;241m.[39mndim [38;5;241m+[39m [38;5;241m1[39m
[1;32m    429[0m axis [38;5;241m=[39m normalize_axis_index(axis, result_ndim)

[0;31mValueError[0m: all input arrays must have the same shape

